// Pastel "toy office" palette: lavender, pink, mint, butter, sky and peach.
export const palette = {
  wall: '#dccdf3',
  wallSide: '#f8d3e3',
  baseboard: '#fff6fb',
  floorSide: '#f6dcec',
  base: '#e9c8e2',
  woodLight: '#f8cfb0',
  wood: '#f1b995',
  woodDark: '#dd9b7c',
  cream: '#fff6ee',
  ink: '#4a3860',
  accent: '#ec74aa',
  lilac: '#c9b4ef',
  pink: '#f7b8d2',
  mint: '#bfe8d6',
  butter: '#fbe7a6',
  sky: '#bfe0f5',
  peach: '#f8c8a8',
  leaf: '#7cc08a',
  leafDark: '#5aa775',
  leafLight: '#a6d9a0',
  pot: '#fff4fa',
  terracotta: '#f6a98f',
  metal: '#b8a7cf',
};
